registry:
  image: registry:2.2.1
  ports:
    - 5000:5000
  container_name: "registry"

clairdata:
  image: alpine
  volumes:
   - /var/local/
  command: "true"
  container_name: "clairdata"

clair:
  image: quay.io/coreos/clair:latest
  volumes:
    - /tmp:/tmp
    - ./config:/config
  volumes_from:
    - clairdata
  ports:
    - 6060:6060
    - 6061:6061
  container_name: "clair"
  command: --config=/config/clair.yml

hyperclair:
  build: .
  volumes:
    - $GOPATH:/go
  ports:
    - 9999:9999
  tty: true
  container_name: "hyperclair"
