language: go
go:
- 1.5
install:
- go get -d -v ./...
- go build -v ./...
deploy:
  provider: releases
  api_key:
    secure: vinoXOszO1dBGKiPLgM7H+LsP5QR4UFGUEC9sQkReJ5GEqqedtwMe8cyRJqxK56nQeciPf3bH+9BrusrjbZVcAHvVlR2+IZPgquame0kbg1xLJMC+qeLR1KXwP/NzzUuSiz+YmTc45/o2b2DkEvKZ9GqJVuX6kz5EQ1SGezOTm3V4DgqYnoxshZKP9Pcc215VTdbGD5TRcFrZ9TqvvhC1qRU43rQGhCtwNT+MB6Nwa8HrWNp290Jpd968lReI9Opp+qRJ5vrimoOIkzPlhlsOxaWTLcBMwjCO/G9T0hIrfaSJF16r2pdwa3pNn3LLQLIKGRZ8nu0J0x8rGjvzJljKwJ3m8f02uHKW8a0ht6Ux9IK4Sn0PDc6+CEUIvkcstiTLzt0QbsDzaFZOR3z6StLqV1aLvZd2gRCJymCk+MMfP+Cl0sGec047J9ObdM4IURFlMjAl51nuRVCAYn+DCbDAUN7xeW0tk90wNJLV+qi/SFqQ/be44u9mQ6HtXPMK7TSSopzY0HcYE3a1HYGoBRryYkNXrYlD754a1CmKMA+cKJ4ggHHhKs/pnps9GL4eH8jKI7WeXzK+KrO8fWdPP2JFtMUU33Yy60EEleOB+nea5mYn5/HrETSEx1JZB/X9eOJM/D9QyoO/abCrRDCq36V0VpbeWzD+CzuzFtuOMzpnMM=
  file: hyperclair
  skip_cleanup: true
  on:
    repo: wemanity-belgium/hyperclair
    tags: true
    branch: master
