language: go
go:
- 1.5
install:
- go get -d -v ./...
- go build -v ./...
deploy:
  provider: releases
  api_key:
    secure: nd7GptnCCo4wRJoAs9lgxkZXoDXNsJVpzmx/VmtBCzoqcbfy3m7VLt/2RUx0805Ll8Sm/M45VJ0cM2jwoJ1CZ2r+svMo4tiAeOESuD2pSu7Yeu3/jEU17nnYVchuGFeCW36TiXcpM+KJrhpKKt/SO9VETD0/7Y0iuYFyeBRo35rHCx3r/9X40DqsdGuaYOBNfHGfTqMX0QbbML4fGvOgqnehYSWRtKqFiXdlyJnn8+wRiUJrrYOmm7RxSnY7XSgJnN7NT1VcA2/96br51tKTMev577/oNt0pvlCfM7mH7JWe5lZBwsecFAgbUjSvuBVfwq1fViZsZsHMj1Hjf+3ARq/SY6iXpDKIb+sYyEgjMib9cTeZQAXX731e2qX7oPeZ1TCdcAawDQGgK9Uu5PfwZrcntRg96UARO7z93w+kw1pwBgYpCxgBHP745cztRPTqj1a5+7vwH6NMK3NCry1o9MJ2AB+Mn6Ep2pFx2uNxILZN9RdZqaNile9QD7EzsqutkfvjD8IOAMYP2AWLhODX4kdm7von+gKvx/SfYMKlNvgLvMS9Hnc7gfI9gV1BJh0FCivFFz9J9gOts4A56rfBqBbdK3eBEUNGxtukU4wle71FuhwAa57O9M89s3SMTLe4lsv+wEh7+gcsbSkp0bMSYNC5uz8KUoRN1bjBbb4lOGc=
  file: hyperclair
  skip_cleanup: true
  on:
    repo: wemanity-belgium/hyperclair
    tags: true
    branch: master
env:
  global:
    GH_REF: "github.com/wemanity-belgium/hyperclair"
    secure: nd7GptnCCo4wRJoAs9lgxkZXoDXNsJVpzmx/VmtBCzoqcbfy3m7VLt/2RUx0805Ll8Sm/M45VJ0cM2jwoJ1CZ2r+svMo4tiAeOESuD2pSu7Yeu3/jEU17nnYVchuGFeCW36TiXcpM+KJrhpKKt/SO9VETD0/7Y0iuYFyeBRo35rHCx3r/9X40DqsdGuaYOBNfHGfTqMX0QbbML4fGvOgqnehYSWRtKqFiXdlyJnn8+wRiUJrrYOmm7RxSnY7XSgJnN7NT1VcA2/96br51tKTMev577/oNt0pvlCfM7mH7JWe5lZBwsecFAgbUjSvuBVfwq1fViZsZsHMj1Hjf+3ARq/SY6iXpDKIb+sYyEgjMib9cTeZQAXX731e2qX7oPeZ1TCdcAawDQGgK9Uu5PfwZrcntRg96UARO7z93w+kw1pwBgYpCxgBHP745cztRPTqj1a5+7vwH6NMK3NCry1o9MJ2AB+Mn6Ep2pFx2uNxILZN9RdZqaNile9QD7EzsqutkfvjD8IOAMYP2AWLhODX4kdm7von+gKvx/SfYMKlNvgLvMS9Hnc7gfI9gV1BJh0FCivFFz9J9gOts4A56rfBqBbdK3eBEUNGxtukU4wle71FuhwAa57O9M89s3SMTLe4lsv+wEh7+gcsbSkp0bMSYNC5uz8KUoRN1bjBbb4lOGc=
